Repository wecode-bootcamp-korea/34-2nd-Fake-Trip-frontend, pull requests merged in 2022-07, with the labels that each got.

#1 [ADD] fontawesome install
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#4 [34기 정현준]ADD: ProductDetail UI
  package-lock.json
  package.json
  public/data/mockdata
  public/data/productDetail.json
  public/images/productDetail/left.png
  public/images/productDetail/right.png
  src/Router.js
  src/config.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/components/CustomerReview/CustomerReview.js
  src/pages/ProductDetail/components/CustomerReview/UserInputContainer.js
  src/pages/ProductDetail/components/DetailHeder/DetailHeader.js
  src/pages/ProductDetail/components/DetailOptional/DetailOptional.js
  src/pages/ProductDetail/components/ProductInformation/ProductInformation.js
  src/pages/ProductDetail/components/ProductNav/ProductNav.js
  src/pages/ProductDetail/components/SideBar/SideBar.js
Labels: 완료

#9 [34기 장류광]PUSH: push footer
  package-lock.json
  package.json
  public/data/locationMockDate.json
  public/data/mockdata.json
  public/images/Nav/myfaketrip_logo(real).png
  src/components/Footer/Footer-style.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav-style.js
  src/components/Nav/Nav.js
  src/components/Nav/NavModal-style.js
  src/components/Nav/NavModal.js
  src/pages/Main/Main-style.js
  src/pages/Main/Main.js
  src/pages/Main/ProductCard-style.js
  src/pages/Main/ProductCard.js
  src/pages/Main/ProductImgSlider-style.js
  src/pages/Main/ProductImgSlider.js
  src/pages/Main/ProfileSlider-style.js
  src/pages/Main/ProfileSlider.js
  src/pages/Main/SearchModal-style.js
  src/pages/Main/SearchModal.js
  src/styles/GlobalStyles.js
Labels: 수정 요청

#10 [ADD] Rating 분포 그래프 기능 추가
  src/config.js
  src/pages/ProductDetail/components/CustomerReview/CustomerReview.js
  src/pages/ProductDetail/components/CustomerReview/UserInputContainer.js
Labels: 멘토 리뷰 요청
